swagger: "2.0"
info:
  description: "This is a server for generating github issue queries based on a language input"
  version: "1.0.0"
  title: "return query for language"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "tscanlan@vmware.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

basePath: "/v1"

schemes:
- "http"
#- "https"
paths:
  /language:
    get:
      summary: "Generate a github issue search query"
      description: "Given string, return a github issue search query string"
      operationId: "api.language.class_instance.generateIssueQuery"
      produces:
      - "application/json"
      parameters:
      - name: "seed"
        in: "query"
        description: "Seed for generating the search terms"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Query"
definitions:
  Query:
    type: "object"
    properties:
      query:
        type: "string"
